server:
    port: 8080
spring:
    datasource:
        url: jdbc:h2:~/test
        driver-class-name: org.h2.Driver
        username: sa
        password: 123456
    jpa:
        database: h2
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                format_sql: true
    h2:
        console:
            path: /h2-console
            enabled: true
